# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubReviewRequests < Formula
  desc "CLI tool to notify when a GitHub PR review is requested"
  homepage "https://github.com/takescoop/github-review-requests"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryanwholey/github-review-requests/releases/download/v0.0.1/github-review-requests_0.0.1_darwin_amd64.tar.gz"
      sha256 "6cc8580b7cce3077285e569fe229e8e8b569e831aa7a74618880e3fcca319e4b"

      def install
        bin.install "grr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryanwholey/github-review-requests/releases/download/v0.0.1/github-review-requests_0.0.1_darwin_arm64.tar.gz"
      sha256 "6b0071e5dd1cac88c89ccf30cca775d9654f925d5d60339a5e4897f666515765"

      def install
        bin.install "grr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryanwholey/github-review-requests/releases/download/v0.0.1/github-review-requests_0.0.1_linux_amd64.tar.gz"
      sha256 "e4e68773a989598f177b89a3387c07dc567ac4e48e5d4df513a691d2fd01cea2"

      def install
        bin.install "grr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanwholey/github-review-requests/releases/download/v0.0.1/github-review-requests_0.0.1_linux_arm64.tar.gz"
      sha256 "543cf8715e3f31b9648aa2437b0293ee6e307f1310afe042b2fcfa2942243360"

      def install
        bin.install "grr"
      end
    end
  end
end
